{% set name = "orthority" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/orthority-{{ version }}.tar.gz
  sha256: 4ab1cd36169ebeac4a6fb1d74d7bf7973be8bf5412dbdc11f6bcc6b3f45098db

build:
  entry_points:
    - oty = orthority.cli:cli
    - simple-ortho = orthority.cli:simple_ortho
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - rasterio >=1.3.6
    - opencv >=4.8
    - pyyaml >=5
    - click >=8
    - tqdm >=4
    - fsspec >=2023.12

test:
  imports:
    - orthority
  commands:
    - pip check
    - oty --help
  requires:
    - pip
    - libopencv *=headless*  # [linux]
    - python {{ python_min }}

about:
  summary: Orthorectification of drone, aerial and satellite imagery.
  license: AGPL-3.0-or-later
  license_file: LICENSE
  home: https://github.com/leftfield-geospatial/orthority
  doc_url: https://orthority.readthedocs.io

extra:
  recipe-maintainers:
    - dugalh
