{% set name = "orthority" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/orthority-{{ version }}.tar.gz
  sha256: 8bfc598231f3d0ff5153052f827ce31a860d584ecfe2d8a56819fb5b55fa7771

build:
  entry_points:
    - oty = orthority.cli:cli
    - simple-ortho = orthority.cli:simple_ortho
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - rasterio >=1.3.6
    - opencv >=4.8
    - pyyaml >=5
    - click >=8
    - tqdm >=4
    - fsspec >=2023.12

test:
  imports:
    - orthority
  commands:
    - pip check
    - oty --help
  requires:
    - pip
    - libopencv *=headless*  # [linux]

about:
  summary: Orthorectification of drone, aerial and satellite imagery.
  license: AGPL-3.0-or-later
  license_file: LICENSE
  home: https://github.com/leftfield-geospatial/orthority
  doc_url: https://orthority.readthedocs.io

extra:
  recipe-maintainers:
    - dugalh
